import { OpenAI } from 'openai';
import dotenv from 'dotenv';

dotenv.config();

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export const requestTripItinerary = async (destination: string, budget: string, duration: number, interests: string[]) => {
  const prompt = `
    Create a detailed day-by-day travel itinerary for a trip to ${destination}.
    - Duration: ${duration} days
    - Budget: ${budget}
    - Interests: ${interests.join(', ')}

    Return the output ONLY as a valid JSON object matching this schema exactly:
    {
      "totalCostEstimate": (number),
      "itinerary": [
        {
          "dayNumber": (number - 1 to N),
          "locations": [
            {
              "id": (give a descriptive string id like "eiffel_tower"),
              "name": (string, name of the place),
              "description": (string, short description),
              "coordinates": [longitude as number, latitude as number],
              "costEstimate": (number, approximate cost in USD)
            }
          ]
        }
      ]
    }

    Ensure the coordinates are valid real-world coordinates [longitude, latitude] for each location.
    Do not wrap the JSON in Markdown. Just output valid raw JSON.
  `;

  try {
    const response = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [{ role: 'user', content: prompt }],
      response_format: { type: 'json_object' },
      temperature: 0.7,
    });

    const content = response.choices[0]?.message?.content;
    
    if (!content) {
      throw new Error("No content generated by OpenAI");
    }

    // Try to parse the JSON
    return JSON.parse(content);

  } catch (error: any) {
    if (error.status === 401) {
      console.error('CRITICAL: Your OpenAI API key is invalid or expired.');
    } else {
      console.error('Error with OpenAI iteration generation:', error.message || error);
    }
    throw new Error('Failed to generate trip itinerary');
  }
};
